name: checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Basic JS check (syntax)
        run: |
          node -e "require('fs').readFileSync('script.js','utf8'); console.log('JS OK')"
      - name: Echo HTML exists
        run: |
          test -f index.html && echo "index.html OK" || (echo "index.html missing" && exit 1)
